export {default as Home } from "./Home"
export {default as Login } from "./Login"
export {default as Register } from "./Register"
export {default as SearchResultList } from "./SearchResultList"
export {default as ThankYou } from "./ThankYou"
export {default as TourDetails } from "./TourDetails"
export {default as Tours } from "./Tours"